name: Build WordDesk

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build WordDesk
        run: dotnet publish WordDesk.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish

      - name: Upload WordDesk
        uses: actions/upload-artifact@v4
        with:
          name: WordDesk-Windows
          path: publish/
